### ISSUE TITLE
Long arboretum use crashes the kernel

### ISSUE THREAD

**Issue by KristinaUlicna** [lowe-lab-ucl/arboretum#76]
I've used a combination of [napari-btrack](https://github.com/lowe-lab-ucl/napari-btrack) + arboretum in sync (maybe that's the problem!) - after clicking on a few cells and checking a multiple lineage trees, the kernel of my notebook from which I opened the napari viewer, crashes. 

This is the trackeback that accumulates in the error log:
```
Traceback (most recent call last):
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 't'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 502, in mousePressEvent
    self._vispy_mouse_press(
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/vispy/app/base.py", line 184, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 990, in on_mouse_press
    self._process_mouse_event(mouse_press_callbacks, event)
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 949, in _process_mouse_event
    mouse_callbacks(layer, event)
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/napari/utils/interactions.py", line 120, in mouse_press_callbacks
    gen = mouse_drag_func(obj, event)
  File "/Volumes/SANDISK/CellCycleDuration/arboretum/napari_arboretum/plugin.py", line 105, in show_tree
    self.track_id = track_id
  File "/Volumes/SANDISK/CellCycleDuration/arboretum/napari_arboretum/util.py", line 35, in track_id
    self.on_track_id_change()
  File "/Volumes/SANDISK/CellCycleDuration/arboretum/napari_arboretum/plugin.py", line 68, in on_track_id_change
    self.property_plotter.track_id = self.track_id
  File "/Volumes/SANDISK/CellCycleDuration/arboretum/napari_arboretum/util.py", line 35, in track_id
    self.on_track_id_change()
  File "/Volumes/SANDISK/CellCycleDuration/arboretum/napari_arboretum/visualisation/base_plotter.py", line 141, in on_track_id_change
    self.plot_property()
  File "/Volumes/SANDISK/CellCycleDuration/arboretum/napari_arboretum/visualisation/base_plotter.py", line 149, in plot_property
    t, prop = self.get_track_properties()
  File "/Volumes/SANDISK/CellCycleDuration/arboretum/napari_arboretum/visualisation/base_plotter.py", line 172, in get_track_properties
    return all_props["t"].values, all_props[self.tracks.color_by].values
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/pandas/core/frame.py", line 3506, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Volumes/SANDISK/CellCycleDuration/virtualenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 't'
```

**Comment by quantumjot** [comment]
I think this is fixed now
